image: node:latest
pages:
  stage: deploy
  script:
  script:
  - npm install -g @angular/cli@7.2.7
  - npm install
  - ng build
  - mv dist/echoes-player/* public/
  artifacts:
    paths:
    - public
  only:
  - master
