image: node:12-alpine
pages:
  stage: deploy
  script:
  script:
  - npm install -g @angular/cli
  - npm install
  - npm install typescript@3.5
  - npm install -g typescript@3.5
  - ng build
  - mv dist/* public/
  artifacts:
    paths:
    - public
  only:
  - master
