image: circleci/node:8.11.3
pages:
  stage: deploy
  script:
  script:
  - npm install -g @angular/cli
  - npm rebuild node-sass
  - npm install
  - ng build
  - mv dist/echoes-player/* public/
  artifacts:
    paths:
    - public
  only:
  - master
