image: node:12-alpine
pages:
  stage: deploy
  script:
  script:
  - npm install -g @angular/cli
  - npm install
  - ng build
  - mv dist/echoes-player/* public/
  artifacts:
    paths:
    - public
  only:
  - master
